### ISSUE TITLE
Altered vertices not visualized -> bug?

### ISSUE THREAD

**Issue by PhilFech123** [mikedh/trimesh#1949]
Hi Trimesh team.

Thank's for this great library. I ran into an issue, which looks to me like a bug: I am loading a simple mesh consisting only of vertices and triangles, add it to a Scene, and visualize it with the SceneViewer. So forth so good, this works. Now I setup a callback function to modify only the vertex coordinates of the mesh (for demonstration purposes I simply add random noise in the example code below). Strangely, this modification does not reach the visualization. But, if I do the same PLUS adding color and changing that also within the callback, then the modification (vertex location and vertex color) is shown in the visualization window (and the framerate drops seriously down)!

Here the code:

```
    import trimesh
    import numpy as np

    file = "fused_tracking_model.ply"
    mesh = trimesh.load_mesh( file )
    mesh.visual = trimesh.visual.ColorVisuals(mesh)
    mesh.visual.face_colors = (0.75, 0.75, 0.2, 1)

    def debug_callback(x):
        mesh.vertices += 0.001 * np.random.random( mesh.vertices.shape )
        x = np.random.uniform(size=1, low=0, high=1)
        # mesh.visual.face_colors = (x[0], 0.75, 0.2, 1)

    scene = trimesh.scene.Scene()
    scene.add_geometry( mesh )
    trimesh.viewer.windowed.SceneViewer(
        scene=scene,
        callback=debug_callback,
        callback_period=0.001,
    )
```
This piece of code shows with high framerate the static mesh loaded from file. Uncommenting the code line within the callback makes the modifications (vertex coordinates and colors) visible at the cost of a serious slow down and the requirement to have had changed the vertex colors also.

To me this looks like a bug. Or do I have a misconception: What is the mechanism to efficiently alter the vertex coordinates with custom computations and let this be reflected within the viewer?

Any help is very welcome!

This is the JSON conda environment I used for testing on my up-do-date Ubunut 22.04 Linux system with Nvidia GeForce GPU:

```
    name: trimesh
    channels:
      - conda-forge
      - defaults
    dependencies:
      - trimesh=3.22.1
      - pyglet      # reported to be v1.5.27
      - numpy       # reported to be v1.24.3
      - scipy       # reported to be v1.10.1
      - pillow      # reported to be v9.5.0
```

Thank's a lot.
