### ISSUE TITLE
Breaking change in 3.10.8 causing materials not to load

### ISSUE THREAD

**Issue by aminya** [mikedh/trimesh#2059]
I have a library that uses Trimesh for mesh loading and modification. After I updated Trimesh to the latest version from `3.9.34` to `4.0.0` I noticed that the materials are no longer loaded correctly. They are replaced with `material_0`.

```
import trimesh
mesh = trimesh.load_mesh('some_mesh.obj')
```

However, after spending an hour trying all the versions by doing a bisect, I found the buggy version: `3.10.8`. The changes in this version break the material loading for me compared to `3.10.7`:

https://github.com/mikedh/trimesh/compare/3.10.7...3.10.8

I have temporarily fixed the issue by pinning the version in

```toml
[tool.poetry.dependencies]
trimesh = "=3.10.7" # 3.10.8 breaks the material loading resulting in no colours
```

Do you know if this breaking change was documented anywhere or was it unexpected? Is there a way I can resolve this or get more information about how the changes affect the materials?
